### PR TITLE
Create composer.json

### PR DESCRIPTION
**Pull request by goaround**
Add a composer.json to make it installable with composer

### CODE REVIEW

**Comment by florianbrinkmann** [comment]
Thanks for the PR! If I understand it correctly, wpackagist.org only works for plugins from the official repo, right? Because the planet feed plugin is not in the repo.

**Comment by goaround** [comment]
No, you can load plugins with a composer.json right from Github. Add this repository as a repository and require `deworg/dewp-planet-feed`:

```json
	"repositories": [
		{
			"type": "github",
			"url": "git@github.com:deworg/dewp-planet-feed"
		}
	],
	"require": {
		"deworg/dewp-planet-feed": ">=0.5.1",
	},
```

**Comment by goaround** [comment]
The https://wpackagist.org repository is not needed. I removed it.

**Comment by florianbrinkmann** [comment]
Okay. I guess when a composer package is installed this way, it just uses the files directly from the repository, and there is no way to specify a release asset? Because the build step for the block editor script is done via GitHub Actions, and only the source files are in the repo.

**Comment by goaround** [comment]
You'are right. I have not thought about it here.

I still tried to solve this problem for me. There is a Composer plugin GitHub Archive Installer which should be perfect here (and for my private themes/plugins) but I can't get it (or its forks) to work with Composer 2: https://github.com/wpscholar/github-archive-installer

Another solution could be the Composer Asset Compiler from Inpsyde: https://github.com/inpsyde/composer-asset-compiler but it runs the build script on composer install/update. It should work but I would prefer the Archive Installer.

Nevertheless, it would be nice if a composer.json was available.

**Comment by goaround** [comment]
Just tried Composer Asset Compiler from Inpsyde and it works really well! Its even possible to use pre-compilation to download the assets right from the release `dewp-planet-feed.zip`

**Comment by florianbrinkmann** [comment]
Okay, cool. Could you provide an example for a `composer.json` with the Composer Asset Compiler in use for the planet repo asset? Then we can add it to the readme file or the wiki. And could you add @Zodiac1978 to the authors section of the `composer.json`?

**Comment by goaround** [comment]
I just run into an issue. The `dewp-planet-feed.zip` will be unziped to the `asset` folder as a hole. At the moment you can't just take the `asset` folder from the zip: https://github.com/inpsyde/composer-asset-compiler/issues/5

For my private plugins/themes I generate an additional `asset.zip`. Would this be an option for this plugin, too?

**Comment by florianbrinkmann** [comment]
> For my private plugins/themes I generate an additional asset.zip. Would this be an option for this plugin, too?

I see nothing that speaks against that. Could you update the GitHub workflow as part of this PR and provide an example config that we can post in the readme or wiki so anyone who wants to install it via composer can use it?

**Comment by goaround** [comment]
Any wishes how the asset.zip should be called? `dewp-planet-feed-assets-0.5.1.zip`, `assets-0.5.1.zip` or just `assets.zip`?

**Comment by florianbrinkmann** [comment]
Just `assets.zip`, the version number was part of an old CI script.

**Comment by goaround** [comment]
Done. Please proofread my _Installation_ part of the README.md.

**Comment by florianbrinkmann** [comment]
I made a few small changes, could you verify that the changes make sense and still describe the composer process correctly?

**Comment by florianbrinkmann** [comment]
Maybe we need to switch to another action for the release asset (https://github.com/actions/upload-release-asset/issues/78), but we will see after running it for the first time.

**Comment by goaround** [comment]
> I made a few small changes, could you verify that the changes make sense and still describe the composer process correctly?

Looks good!

> Maybe we need to switch to another action for the release asset ([actions/upload-release-asset#78](https://github.com/actions/upload-release-asset/issues/78)), but we will see after running it for the first time.

I use https://github.com/JasonEtco/upload-to-release but last release Feb 2019...

**Comment by florianbrinkmann** [comment]
> I use https://github.com/JasonEtco/upload-to-release but last release Feb 2019...

Thanks for the tip!

**Comment by florianbrinkmann** [comment]
And thanks again for the PR :)

**Comment by florianbrinkmann** [comment]
I just released a beta version with the modified GitHub action. I will test it and release the final version — I have no idea, why I have not released 0.5.2 last year 🙈

**Pull request merged**
